# Wikibase with Query Service
#
# This docker-compose example can be used to pull the images from docker hub.
#
# Examples:
#
# Access Wikibase via "http://localhost:8181"
#   (or "http://$(docker-machine ip):8181" if using docker-machine)
#
# Access Query Service via "http://localhost:8282"
#   (or "http://$(docker-machine ip):8282" if using docker-machine)
version: '3'

services:
  ## Script to setup jenkins to run proteinboxbot bots
  ## available as aa.bb.cc.dd:8080
  proteinboxbot:
    image: andrawaag/genewiki-jenkins:latest
    ports:
      - 8080:8080
    volumes:
      - proteinboxbot-jenkins-home:/var/jenkins_home
    env_file:
      - .env
  
volumes:
  proteinboxbot-jenkins-home:

